### ISSUE TITLE
iTunes feed

### ISSUE THREAD

**Issue by testbrian** [moumar/ruby-mp3info#46]
Is there some way to add iTunes attributes to an mp3? Would this make any sense in this library?
I'm thinking a new wrapper tag like mp3.itunes which can return all the various extra attributes iTunes often asks for for a podcast feed?

**Comment by iarobinson** [comment]
In the case of podcasting, iTunes pulls all data from the RSS feed. 

The exception being that the image added to the .mp3's ID3 information will display on the iPhone when playing a podcast. I believe this is just the mp3 player reading the mp3, rather than iTunes relaying the information.

If we use separate episode art to tag a .mp3, iTunes will still display the show art in their Top Episode categories. Therefore, we know they aren't relaying the art tagged in the .mp3 on the actual server. Indeed, they are using the show art which is included in the RSS feed.

That leads me to believe that iTunes doesn't actually read the ID3 information and focuses solely on the information provided by the RSS feed.

Therefore, I don't think it would be worthwhile to write iTunes attributes into a podcast .mp3. However, if I don't know what I'm talking about, I'd love to hear your response.
